=== gitswapnil0911/trainingAssignments/JAVA/src/com/jpm/xml/dtd/externaldtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT countries (country)>
        <!ELEMENT country (name, capital, currency, description)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT capital (#PCDATA)>
        <!ELEMENT currency (#PCDATA)>
        <!ELEMENT description (continent, language)>
        <!ELEMENT continent (#PCDATA)>
        <!ELEMENT language (#PCDATA)>

=== gitswapnil0911/trainingAssignments/JAVA/out/production/JAVA/com/jpm/xml/dtd/externaldtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE countries SYSTEM "D:\Swapnil\JAVA\src\com\jpm\xml\dtd\externaldtd.dtd"><!---SYSTEM is used if DTD is avaialbale locally on system if its on servere then Public has to be used and provide url-->
<countries>
    <country>
        <name>India</name>
        <capital>New Delhi</capital>
        <currency>INR</currency>
        <description>
            <continent>Asia</continent>
            <language>Hindi</language>
        </description>
    </country>
</countries>
