=== gitswapnil0911/trainingAssignments/JAVA/out/production/JAVA/com/jpm/xml/dtd/movies.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT movies (movie)+>
        <!ELEMENT movie (name, release-date, details)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT release-date (dd, mm, yy)>
        <!ELEMENT dd (#PCDATA)>
        <!ELEMENT mm (#PCDATA)>
        <!ELEMENT yy (#PCDATA)>
        <!ELEMENT details (director, producer, actors, collection)>
        <!ELEMENT director (#PCDATA)>
        <!ELEMENT producer (#PCDATA)>
        <!ELEMENT actors (actor+)>
        <!ELEMENT actor (#PCDATA)>
        <!ELEMENT collection (#PCDATA)>
        <!ATTLIST movie language (HINDI | ENGLISH) #REQUIRED>
        <!ATTLIST movie genre (COMEDY | ACTION | THRILLER | SUSPENSE) #REQUIRED>

=== gitswapnil0911/trainingAssignments/JAVA/src/com/jpm/xml/dtd/moviesdtdimpl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "D:\Swapnil\JAVA\src\com\jpm\xml\dtd\movies.dtd"><!---SYSTEM is used if DTD is avaialbale locally on system if its on servere then Public has to be used and provide url-->
<movies>
    <movie language="ENGLISH" genre="ACTION">
        <name>War</name>
        <release-date>
            <dd>02</dd>
            <mm>10</mm>
            <yy>2019</yy>
        </release-date>
        <details>
            <director>Sidhharth</director>
            <producer>Karan</producer>
            <actors>
                <actor>Hrithik</actor>
                <actor>Tiger</actor>
            </actors>
            <collection>200CR</collection>
        </details>
        </movie>
</movies>
