=== gitswapnil0911/trainingAssignments/JAVA/out/production/JAVA/com/jpm/xml/xsd/attributes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.library.com"
        elementFormDefault="qualified">
    <element name="books">
        <complexType>
            <sequence>
            <element name="book" minOccurs="2" maxOccurs="5">
                <complexType>
                    <sequence>
                        <element name="title" type="string"/>
                        <element name="author" type="string"/>
                        <element name="price" type="float"/>
                    </sequence>
                    <attribute name="language" use="required"/>
                    <attribute name="type" use="optional" default="IT"/>
                </complexType>
            </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== gitswapnil0911/trainingAssignments/JAVA/src/com/jpm/xml/xsd/attributes.xml
<?xml version="1.0" encoding="UTF-8"?>
<lib:books xmlns:lib="http://www.library.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.library.com attributes.xsd">
  <!--2 to 5 repetitions:-->
  <lib:book language="English" type="IT">
    <lib:title>Alchemist</lib:title>
    <lib:author>Dan</lib:author>
    <lib:price>400.50</lib:price>
  </lib:book>
  <lib:book language="Marathi" type="IT">
    <lib:title>Mrutyunjay</lib:title>
    <lib:author>Patil</lib:author>
    <lib:price>700.67</lib:price>
  </lib:book>
</lib:books>
